<?php

namespace MP\LogistiqueBundle\Repository;

use MP\LogistiqueBundle\Entity\Employer;
use Doctrine\ORM\EntityRepository;
/**
 * EmployerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployerRepository extends \Doctrine\ORM\EntityRepository
{
    public function loadAllEmployer() {

        $queryBuilder = $this->createQueryBuilder('E');
        $queryBuilder->add('select', 'E');
        $queryBuilder->add('from', 'LogistiqueBundle:Employer E');
        $query   = $queryBuilder->getQuery();

        return $query;
    }
}
